# Generated by Django 4.1.2 on 2022-10-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
