# Generated by Django 4.1.2 on 2022-10-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_student_subjects_delete_subject'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='age must be greater than 5',
        ),
    ]
