# Generated by Django 4.1.2 on 2022-10-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_subject_student_subjects'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('age__gt', 5)), name='age must be greater than 5'),
        ),
    ]
