# Generated by Django 4.1.2 on 2022-10-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_student_age must be greater than 5'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='mark must be greater than 0',
        ),
    ]
