# Generated by Django 4.1.2 on 2022-10-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_age must be greater than 5'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('mark__gt', 0)), name='mark must be greater than 0'),
        ),
    ]
