# Generated by Django 4.1.2 on 2022-10-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
